remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: auto
title: DSA Problems
description: DSA Problems and their solutions.

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

include: [".htaccess", ".md"]

navigation:
  - name: LeetCode
    link: https://vaibhavvikas.ml/dsa-problems/
  - name: General 
    link: https://vaibhavvikas.ml/dsa-problems/general.html
