remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: auto
title: DSA Problems
description: DSA Problems and their solutions.

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

include: [".htaccess", ".md"]

platforms:
  - name: Leetcode
    icon: <i class="fa-brands fa-codiepie"></i>
    link: https://vaibhavvikas.github.io/dsa-problems/
  - name: General
    icon: <i class="fa-solid fa-file-code"></i>
    link: https://vaibhavvikas.github.io/dsa-problems/general.html
  - name: SDE Sheet
    icon: <i class="fa-solid fa-microchip"></i>
    link: https://vaibhavvikas.github.io/dsa-problems/sde-sheet.html
  - name: Interview
    icon: <i class="fa-solid fa-user-secret"></i>
    link: https://vaibhavvikas.github.io/dsa-problems/interview.html
